/**
 * Terms and Conditions page.
 * Displays comprehensive, professional terms and conditions with multilingual support.
 */

import React from 'react';
import { Link } from 'react-router-dom';
import { useTranslation } from 'react-i18next';
import { Layout } from '@components/Layout';

const LegalTerms: React.FC = () => {
  const { t } = useTranslation();
  
  return (
    <Layout>
      <div className="step-container">
        <div className="step-content" style={{ maxWidth: '950px', margin: '0 auto', padding: '2rem' }}>
          <h1 style={{ marginBottom: '1rem' }}>{t('legal.terms')}</h1>
          
          <div style={{ 
            marginBottom: '2rem', 
            padding: '1rem', 
            backgroundColor: 'var(--color-bg-secondary)', 
            borderRadius: 'var(--radius-md)',
            border: '1px solid var(--color-border)'
          }}>
            <strong>{t('legal.base_language_notice')}</strong>
          </div>
          
          <div style={{ 
            lineHeight: '1.8', 
            color: 'var(--color-text-secondary)',
            fontSize: '0.95rem'
          }}>
            <div style={{ marginBottom: '2rem', paddingBottom: '1rem', borderBottom: '2px solid var(--color-border)' }}>
              <p><strong>{t('legal.last_updated')}</strong>: January 8, 2025</p>
              <p><strong>{t('legal.version')}</strong>: 1.0</p>
            </div>
            
            <section style={{ marginBottom: '2.5rem' }}>
              <h2 style={{ color: 'var(--color-text-primary)', marginBottom: '1rem', fontSize: '1.5rem' }}>1. Acceptance of Terms</h2>
              <p>
                By accessing and using the ShortlistAI CV Analysis Platform ("Platform", "Service"), you ("User", "you", "your") agree to be bound by these Terms and Conditions ("Terms", "Agreement"). If you do not agree to these Terms, you must not access or use the Platform.
              </p>
              <p style={{ marginTop: '0.75rem' }}>
                These Terms constitute a legally binding agreement between you and ShortlistAI. By clicking "I agree", creating an account, or using the Platform, you acknowledge that you have read, understood, and agree to be bound by these Terms.
              </p>
              <p style={{ marginTop: '0.75rem' }}>
                If you are using the Platform on behalf of an organization, you represent and warrant that you have the authority to bind that organization to these Terms.
              </p>
            </section>

            <section style={{ marginBottom: '2.5rem' }}>
              <h2 style={{ color: 'var(--color-text-primary)', marginBottom: '1rem', fontSize: '1.5rem' }}>2. Definitions</h2>
              <p>For the purposes of these Terms:</p>
              <ul style={{ marginLeft: '2rem', marginTop: '0.5rem' }}>
                <li><strong>"Platform"</strong> means the ShortlistAI CV Analysis Platform, including all websites, applications, services, and software.</li>
                <li><strong>"Service"</strong> means the CV analysis services provided through the Platform.</li>
                <li><strong>"User"</strong> means any individual or entity that accesses or uses the Platform.</li>
                <li><strong>"Content"</strong> means any data, text, files, documents, CVs, job postings, or other materials uploaded through the Platform.</li>
                <li><strong>"AI Analysis"</strong> means any analysis, evaluation, scoring, or recommendation generated by artificial intelligence systems.</li>
                <li><strong>"Personal Data"</strong> means any information relating to an identified or identifiable natural person.</li>
              </ul>
            </section>

            <section style={{ marginBottom: '2.5rem' }}>
              <h2 style={{ color: 'var(--color-text-primary)', marginBottom: '1rem', fontSize: '1.5rem' }}>3. Description of Service</h2>
              <p>ShortlistAI provides a free, AI-powered CV analysis service that enables:</p>
              <div style={{ marginTop: '1rem' }}>
                <h3 style={{ color: 'var(--color-text-primary)', marginBottom: '0.5rem' }}>3.1 Interviewer Mode</h3>
                <ul style={{ marginLeft: '2rem', marginTop: '0.5rem' }}>
                  <li>Comparison and evaluation of multiple CVs against job postings</li>
                  <li>Automated ranking and scoring of candidates</li>
                  <li>Generation of custom interview questions</li>
                  <li>Production of comprehensive analysis reports</li>
                  <li>Email summaries and PDF reports</li>
                </ul>
              </div>
              <div style={{ marginTop: '1rem' }}>
                <h3 style={{ color: 'var(--color-text-primary)', marginBottom: '0.5rem' }}>3.2 Candidate Mode</h3>
                <ul style={{ marginLeft: '2rem', marginTop: '0.5rem' }}>
                  <li>Analysis of candidate fit for specific positions</li>
                  <li>Identification of strengths and gaps</li>
                  <li>Prediction of likely interview questions</li>
                  <li>Generation of suggested answers and preparation materials</li>
                  <li>Creation of personalized introduction pitches</li>
                </ul>
              </div>
              <div style={{ marginTop: '1rem' }}>
                <h3 style={{ color: 'var(--color-text-primary)', marginBottom: '0.5rem' }}>3.3 Headhunting Database</h3>
                <ul style={{ marginLeft: '2rem', marginTop: '0.5rem' }}>
                  <li>Storage of CVs and candidate information for future opportunities</li>
                  <li>Matching of candidates to relevant job opportunities</li>
                  <li>Contact management for recruitment purposes</li>
                </ul>
              </div>
              <p style={{ marginTop: '1rem', fontStyle: 'italic' }}>
                The Service is provided "as is" and may be modified, updated, or discontinued at any time without prior notice.
              </p>
            </section>

            <section style={{ marginBottom: '2.5rem' }}>
              <h2 style={{ color: 'var(--color-text-primary)', marginBottom: '1rem', fontSize: '1.5rem' }}>4. Eligibility and Account Requirements</h2>
              <div style={{ marginBottom: '1rem' }}>
                <h3 style={{ color: 'var(--color-text-primary)', marginBottom: '0.5rem' }}>4.1 Eligibility</h3>
                <p>You must be at least 16 years of age to use the Platform. If you are under 18, you represent that you have obtained parental or guardian consent to use the Platform.</p>
              </div>
              <div style={{ marginBottom: '1rem' }}>
                <h3 style={{ color: 'var(--color-text-primary)', marginBottom: '0.5rem' }}>4.2 Account Requirements</h3>
                <ul style={{ marginLeft: '2rem', marginTop: '0.5rem' }}>
                  <li><strong>Public Users (Interviewers and Candidates)</strong>: No account creation is required. You may use the Platform anonymously.</li>
                  <li><strong>Admin Users</strong>: Account creation and authentication are required. You are responsible for maintaining the confidentiality of your login credentials.</li>
                </ul>
              </div>
              <div>
                <h3 style={{ color: 'var(--color-text-primary)', marginBottom: '0.5rem' }}>4.3 Account Security</h3>
                <p>If you are an Admin user, you are solely responsible for maintaining the confidentiality of your account credentials, all activities that occur under your account, and notifying us immediately of any unauthorized use.</p>
              </div>
            </section>

            <section style={{ marginBottom: '2.5rem' }}>
              <h2 style={{ color: 'var(--color-text-primary)', marginBottom: '1rem', fontSize: '1.5rem' }}>5. User Roles and Responsibilities</h2>
              <div style={{ marginBottom: '1rem' }}>
                <h3 style={{ color: 'var(--color-text-primary)', marginBottom: '0.5rem' }}>5.1 Interviewers</h3>
                <p>Interviewers are users who upload job postings and CVs to evaluate candidates. Interviewers agree to:</p>
                <ul style={{ marginLeft: '2rem', marginTop: '0.5rem' }}>
                  <li>Only upload CVs for candidates who have provided consent</li>
                  <li>Use the Platform in compliance with applicable employment and data protection laws</li>
                  <li>Not use the Platform for discriminatory hiring practices</li>
                  <li>Verify the accuracy of information provided</li>
                </ul>
              </div>
              <div style={{ marginBottom: '1rem' }}>
                <h3 style={{ color: 'var(--color-text-primary)', marginBottom: '0.5rem' }}>5.2 Candidates</h3>
                <p>Candidates are users who upload their CV and a job posting to receive preparation guidance. Candidates agree to:</p>
                <ul style={{ marginLeft: '2rem', marginTop: '0.5rem' }}>
                  <li>Provide accurate and truthful information</li>
                  <li>Not misrepresent qualifications or experience</li>
                  <li>Understand that AI analysis is advisory only</li>
                </ul>
              </div>
              <div>
                <h3 style={{ color: 'var(--color-text-primary)', marginBottom: '0.5rem' }}>5.3 Admin Users</h3>
                <p>Admin users are platform administrators who manage data, AI configuration, and system settings. Admin users agree to use administrative access responsibly and ethically, not share login credentials, and comply with all applicable data protection regulations.</p>
              </div>
            </section>

            <section style={{ marginBottom: '2.5rem' }}>
              <h2 style={{ color: 'var(--color-text-primary)', marginBottom: '1rem', fontSize: '1.5rem' }}>6. Data Collection and Storage</h2>
              <div style={{ marginBottom: '1rem' }}>
                <h3 style={{ color: 'var(--color-text-primary)', marginBottom: '0.5rem' }}>6.1 Information Collected</h3>
                <p>When you use the Platform, we collect:</p>
                <ul style={{ marginLeft: '2rem', marginTop: '0.5rem' }}>
                  <li><strong>Personal Information</strong>: Full name, email address, phone number, country, company name (optional)</li>
                  <li><strong>Content Information</strong>: Job postings, CV files, extracted text, analysis requests</li>
                  <li><strong>AI-Generated Information</strong>: Analysis results, scores, rankings, interview questions, recommendations</li>
                  <li><strong>Technical Information</strong>: IP address, browser type, device information, usage patterns</li>
                </ul>
              </div>
              <div style={{ marginBottom: '1rem' }}>
                <h3 style={{ color: 'var(--color-text-primary)', marginBottom: '0.5rem' }}>6.2 Purpose of Collection</h3>
                <p>We collect this information to provide the CV analysis service, improve our AI models, build a headhunting database, contact you about opportunities (with consent), ensure Platform security, and comply with legal obligations.</p>
              </div>
              <div>
                <h3 style={{ color: 'var(--color-text-primary)', marginBottom: '0.5rem' }}>6.3 Consent and Legal Basis</h3>
                <p>By using the Platform, you explicitly consent to storage and processing of your data. Our legal basis includes consent, legitimate interests, contract performance, and legal obligations.</p>
              </div>
            </section>

            <section style={{ marginBottom: '2.5rem' }}>
              <h2 style={{ color: 'var(--color-text-primary)', marginBottom: '1rem', fontSize: '1.5rem' }}>7. AI Processing and Third-Party Services</h2>
              <div style={{ marginBottom: '1rem' }}>
                <h3 style={{ color: 'var(--color-text-primary)', marginBottom: '0.5rem' }}>7.1 AI Providers</h3>
                <p>Your data may be processed by external AI providers, including:</p>
                <ul style={{ marginLeft: '2rem', marginTop: '0.5rem' }}>
                  <li>Google Gemini</li>
                  <li>OpenAI (GPT models)</li>
                  <li>Anthropic (Claude)</li>
                  <li>Kimi</li>
                  <li>Minimax</li>
                </ul>
                <p style={{ marginTop: '0.75rem' }}>We may add, remove, or change AI providers at any time without prior notice.</p>
              </div>
              <div style={{ marginBottom: '1rem' }}>
                <h3 style={{ color: 'var(--color-text-primary)', marginBottom: '0.5rem' }}>7.2 Data Sent to AI Providers</h3>
                <p>We send job posting text, CV text, and analysis requests to AI providers. We do NOT send passwords, API keys, payment information, or complete database records.</p>
              </div>
              <div style={{ 
                marginTop: '1rem', 
                padding: '1rem', 
                backgroundColor: 'var(--color-bg-secondary)', 
                borderRadius: 'var(--radius-md)',
                border: '1px solid var(--color-border)'
              }}>
                <h3 style={{ color: 'var(--color-text-primary)', marginBottom: '0.5rem' }}>7.4 AI Limitations and Disclaimers</h3>
                <p><strong>Critical Disclaimer</strong>: AI analysis is advisory only and should not be the sole basis for hiring decisions or career choices. AI systems may produce inaccurate, incomplete, or biased results. Human judgment is always required when making hiring or career decisions.</p>
                <p style={{ marginTop: '0.75rem' }}>You acknowledge that you are solely responsible for decisions made based on AI analysis, and we are not liable for any consequences arising from reliance on AI analysis.</p>
              </div>
            </section>

            <section style={{ marginBottom: '2.5rem' }}>
              <h2 style={{ color: 'var(--color-text-primary)', marginBottom: '1rem', fontSize: '1.5rem' }}>8. Headhunting Database</h2>
              <p>All CVs and candidate information submitted through the Platform are stored in a headhunting database for matching candidates to future job opportunities. Only authorized Admin users have access to the full database. With your explicit consent, we may contact you about relevant job opportunities.</p>
              <p style={{ marginTop: '0.75rem' }}>You may withdraw consent for future contact at any time by contacting us at <a href={`mailto:${t('legal.contact.privacy')}`} style={{ color: 'var(--color-primary)' }}>{t('legal.contact.privacy')}</a>.</p>
            </section>

            <section style={{ marginBottom: '2.5rem' }}>
              <h2 style={{ color: 'var(--color-text-primary)', marginBottom: '1rem', fontSize: '1.5rem' }}>9. User Obligations and Acceptable Use</h2>
              <div style={{ marginBottom: '1rem' }}>
                <h3 style={{ color: 'var(--color-text-primary)', marginBottom: '0.5rem' }}>9.1 General Obligations</h3>
                <p>You agree to provide accurate information, use the Platform only for lawful purposes, comply with all applicable laws, and respect the rights of other users and third parties.</p>
              </div>
              <div style={{ marginBottom: '1rem' }}>
                <h3 style={{ color: 'var(--color-text-primary)', marginBottom: '0.5rem' }}>9.2 Content Standards</h3>
                <p>All Content you upload must be accurate, truthful, not violate third-party rights, not contain malicious code, and comply with applicable laws.</p>
              </div>
              <div>
                <h3 style={{ color: 'var(--color-text-primary)', marginBottom: '0.5rem' }}>9.3 Prohibited Activities</h3>
                <p>You agree NOT to:</p>
                <ul style={{ marginLeft: '2rem', marginTop: '0.5rem' }}>
                  <li>Upload CVs without the candidate's knowledge or explicit consent</li>
                  <li>Use the Platform for discriminatory hiring practices</li>
                  <li>Attempt to gain unauthorized access to the Platform</li>
                  <li>Reverse engineer, decompile, or disassemble any part of the Platform</li>
                  <li>Use automated systems to access the Platform without permission</li>
                  <li>Interfere with or disrupt the Platform</li>
                </ul>
              </div>
            </section>

            <section style={{ marginBottom: '2.5rem' }}>
              <h2 style={{ color: 'var(--color-text-primary)', marginBottom: '1rem', fontSize: '1.5rem' }}>10. Intellectual Property Rights</h2>
              <p>ShortlistAI owns all code, design, content, trademarks, and intellectual property of the Platform. You are granted a limited, non-exclusive license to access and use the Platform for its intended purposes.</p>
              <p style={{ marginTop: '0.75rem' }}>You retain ownership of Content you upload, but by uploading, you grant ShortlistAI a worldwide, non-exclusive, royalty-free license to store, process, and use the Content to provide the Service, include it in our headhunting database, and use anonymized Content for service improvement.</p>
            </section>

            <section style={{ marginBottom: '2.5rem' }}>
              <h2 style={{ color: 'var(--color-text-primary)', marginBottom: '1rem', fontSize: '1.5rem' }}>11. Privacy and Data Protection</h2>
              <p>Your use of the Platform is also governed by our <Link to="/legal/privacy" style={{ color: 'var(--color-primary)' }}>Privacy Policy</Link>, which explains how we collect, use, store, and protect your personal data.</p>
              <p style={{ marginTop: '0.75rem' }}>You have certain rights regarding your personal data, including access, correction, deletion, portability, and the right to object to processing. For details, see our Privacy Policy or contact us at <a href={`mailto:${t('legal.contact.privacy')}`} style={{ color: 'var(--color-primary)' }}>{t('legal.contact.privacy')}</a>.</p>
            </section>

            <section style={{ marginBottom: '2.5rem' }}>
              <h2 style={{ color: 'var(--color-text-primary)', marginBottom: '1rem', fontSize: '1.5rem' }}>12. Service Availability and Modifications</h2>
              <p>We strive to maintain high availability but do not guarantee uninterrupted service, specific uptime percentages, or immediate response times. The Platform may be temporarily unavailable due to maintenance, technical issues, or force majeure events.</p>
              <p style={{ marginTop: '0.75rem' }}>We reserve the right to modify, suspend, or discontinue any feature at any time without prior notice. Some features may be marked as "beta" or "experimental" and may have limited functionality or stability.</p>
            </section>

            <section style={{ marginBottom: '2.5rem' }}>
              <h2 style={{ color: 'var(--color-text-primary)', marginBottom: '1rem', fontSize: '1.5rem' }}>13. Payment and Billing</h2>
              <p>The Platform is currently provided free of charge. We reserve the right to introduce premium or paid features in the future, change pricing models with advance notice, or implement usage limits or restrictions.</p>
              <p style={{ marginTop: '0.75rem' }}>If we introduce paid features, pricing will be clearly disclosed, you will be notified before charges apply, and you may cancel at any time.</p>
            </section>

            <section style={{ marginBottom: '2.5rem' }}>
              <h2 style={{ color: 'var(--color-text-primary)', marginBottom: '1rem', fontSize: '1.5rem' }}>14. Liability and Disclaimers</h2>
              <div style={{ 
                padding: '1rem', 
                backgroundColor: 'var(--color-bg-secondary)', 
                borderRadius: 'var(--radius-md)',
                border: '1px solid var(--color-border)'
              }}>
                <p><strong>THE PLATFORM IS PROVIDED "AS IS" AND "AS AVAILABLE" WITHOUT WARRANTIES OF ANY KIND.</strong></p>
                <p style={{ marginTop: '0.75rem' }}>We do not guarantee accuracy of AI analysis, job placement, service availability, or specific results. To the maximum extent permitted by law, we are not liable for hiring decisions made based on our analysis, lost opportunities, data loss, service interruptions, or actions of third parties.</p>
                <p style={{ marginTop: '0.75rem' }}>In no event shall our total liability exceed the amount you paid to us in the twelve (12) months preceding the claim, or one hundred dollars ($100), whichever is greater.</p>
              </div>
            </section>

            <section style={{ marginBottom: '2.5rem' }}>
              <h2 style={{ color: 'var(--color-text-primary)', marginBottom: '1rem', fontSize: '1.5rem' }}>15. Indemnification</h2>
              <p>You agree to indemnify, defend, and hold harmless ShortlistAI, its affiliates, officers, directors, employees, agents, and licensors from and against any and all claims, damages, obligations, losses, liabilities, costs, or expenses arising from your use of the Platform, violation of these Terms, violation of any third-party right, or Content you upload.</p>
            </section>

            <section style={{ marginBottom: '2.5rem' }}>
              <h2 style={{ color: 'var(--color-text-primary)', marginBottom: '1rem', fontSize: '1.5rem' }}>16. Account Termination and Suspension</h2>
              <p>You may stop using the Platform at any time. We reserve the right to terminate or suspend your access, remove your account and Content, or block your access if you violate these Terms, engage in fraudulent or illegal activities, or use the Platform in a manner that could damage the Platform.</p>
              <p style={{ marginTop: '0.75rem' }}>Upon termination, your right to use the Platform will immediately cease, and we may delete your account and Content (subject to legal retention requirements).</p>
            </section>

            <section style={{ marginBottom: '2.5rem' }}>
              <h2 style={{ color: 'var(--color-text-primary)', marginBottom: '1rem', fontSize: '1.5rem' }}>17. Data Retention and Deletion</h2>
              <p>We retain your data for as long as necessary to provide the Service, fulfill legitimate business purposes, comply with legal obligations, resolve disputes, and enforce our agreements.</p>
              <p style={{ marginTop: '0.75rem' }}>You have the right to request deletion of your data at any time by contacting us at <a href={`mailto:${t('legal.contact.privacy')}`} style={{ color: 'var(--color-primary)' }}>{t('legal.contact.privacy')}</a>. We will process deletion requests within 30 days, subject to legal requirements and technical limitations.</p>
            </section>

            <section style={{ marginBottom: '2.5rem' }}>
              <h2 style={{ color: 'var(--color-text-primary)', marginBottom: '1rem', fontSize: '1.5rem' }}>18. Dispute Resolution</h2>
              <p>These Terms are governed by the laws of the jurisdiction where ShortlistAI operates. Any disputes shall first be resolved through good-faith negotiation for 30 days. If unresolved, disputes will be handled through mediation (if agreed), binding arbitration, or courts of competent jurisdiction as required by applicable law.</p>
              <p style={{ marginTop: '0.75rem' }}>To the extent permitted by applicable law, you waive any right to participate in class action lawsuits against ShortlistAI.</p>
            </section>

            <section style={{ marginBottom: '2.5rem' }}>
              <h2 style={{ color: 'var(--color-text-primary)', marginBottom: '1rem', fontSize: '1.5rem' }}>19. Force Majeure</h2>
              <p>We shall not be liable for any failure or delay in performance resulting from circumstances beyond our reasonable control, including acts of God, natural disasters, war, terrorism, government actions, internet or telecommunications failures, cyberattacks, pandemics, or other force majeure events.</p>
            </section>

            <section style={{ marginBottom: '2.5rem' }}>
              <h2 style={{ color: 'var(--color-text-primary)', marginBottom: '1rem', fontSize: '1.5rem' }}>20. Assignment</h2>
              <p>You may not assign, transfer, or delegate your rights or obligations under these Terms without our prior written consent. We may assign these Terms to any affiliate, successor in a merger or acquisition, or third party with proper notice to you.</p>
            </section>

            <section style={{ marginBottom: '2.5rem' }}>
              <h2 style={{ color: 'var(--color-text-primary)', marginBottom: '1rem', fontSize: '1.5rem' }}>21. Waiver</h2>
              <p>Our failure to enforce any provision of these Terms does not constitute a waiver of that provision or any other provision. No waiver shall be effective unless made in writing and signed by the waiving party.</p>
            </section>

            <section style={{ marginBottom: '2.5rem' }}>
              <h2 style={{ color: 'var(--color-text-primary)', marginBottom: '1rem', fontSize: '1.5rem' }}>22. Severability</h2>
              <p>If any provision of these Terms is found to be invalid, illegal, or unenforceable, the remaining provisions shall continue in full force and effect. The invalid provision shall be modified to the minimum extent necessary to make it valid and enforceable.</p>
            </section>

            <section style={{ marginBottom: '2.5rem' }}>
              <h2 style={{ color: 'var(--color-text-primary)', marginBottom: '1rem', fontSize: '1.5rem' }}>23. Entire Agreement</h2>
              <p>These Terms, together with our <Link to="/legal/privacy" style={{ color: 'var(--color-primary)' }}>Privacy Policy</Link> and <Link to="/legal/cookies" style={{ color: 'var(--color-primary)' }}>Cookie Policy</Link>, constitute the entire agreement between you and ShortlistAI regarding the use of the Platform and supersede all prior agreements.</p>
            </section>

            <section style={{ marginBottom: '2.5rem' }}>
              <h2 style={{ color: 'var(--color-text-primary)', marginBottom: '1rem', fontSize: '1.5rem' }}>24. Changes to Terms</h2>
              <p>We reserve the right to modify these Terms at any time. We will notify you of material changes by posting the updated Terms on the Platform, updating the "Last Updated" date, and sending email notifications (for registered users).</p>
              <p style={{ marginTop: '0.75rem' }}>Your continued use of the Platform after changes become effective constitutes your acceptance of the modified Terms. If you do not agree to the changes, you must stop using the Platform.</p>
            </section>

            <section style={{ marginBottom: '2.5rem' }}>
              <h2 style={{ color: 'var(--color-text-primary)', marginBottom: '1rem', fontSize: '1.5rem' }}>25. Contact Information</h2>
              <p>For questions, concerns, or notices regarding these Terms:</p>
              <p style={{ marginTop: '0.75rem' }}>
                <strong>Legal Inquiries</strong>: <a href={`mailto:${t('legal.contact.legal')}`} style={{ color: 'var(--color-primary)' }}>{t('legal.contact.legal')}</a><br />
                <strong>Privacy Inquiries</strong>: <a href={`mailto:${t('legal.contact.privacy')}`} style={{ color: 'var(--color-primary)' }}>{t('legal.contact.privacy')}</a>
              </p>
              <p style={{ marginTop: '0.75rem' }}>We will respond to inquiries within a reasonable time frame, typically within 5-10 business days.</p>
            </section>

            <div style={{ 
              marginTop: '3rem', 
              padding: '1.5rem', 
              backgroundColor: 'var(--color-bg-secondary)', 
              borderRadius: 'var(--radius-md)',
              border: '1px solid var(--color-border)'
            }}>
              <h3 style={{ color: 'var(--color-text-primary)', marginBottom: '1rem' }}>Summary</h3>
              <p style={{ marginBottom: '0.75rem' }}>These Terms govern your use of the ShortlistAI Platform. Key points:</p>
              <ul style={{ marginLeft: '1.5rem' }}>
                <li>✅ You must be at least 16 years old to use the Platform</li>
                <li>✅ The Platform is currently free but may introduce paid features</li>
                <li>✅ AI analysis is advisory only - human judgment is always required</li>
                <li>✅ You retain ownership of your Content but grant us a license to use it</li>
                <li>✅ We may modify these Terms at any time with notice</li>
                <li>✅ Your use of the Platform is subject to our Privacy Policy and Cookie Policy</li>
                <li>✅ We are not liable for decisions made based on AI analysis</li>
              </ul>
            </div>

            <div style={{ 
              marginTop: '2rem', 
              padding: '1.5rem', 
              backgroundColor: 'var(--color-bg-secondary)', 
              borderRadius: 'var(--radius-md)',
              border: '1px solid var(--color-border)'
            }}>
              <h3 style={{ color: 'var(--color-text-primary)', marginBottom: '1rem' }}>Related Documents</h3>
              <ul style={{ marginLeft: '1.5rem' }}>
                <li><Link to="/legal/privacy" style={{ color: 'var(--color-primary)' }}>Privacy Policy</Link></li>
                <li><Link to="/legal/cookies" style={{ color: 'var(--color-primary)' }}>Cookie Policy</Link></li>
              </ul>
            </div>
          </div>
          
          <div style={{ marginTop: '2rem', paddingTop: '1.5rem', borderTop: '1px solid var(--color-border)' }}>
            <Link to="/" style={{ color: 'var(--color-primary)', textDecoration: 'none' }}>
              {t('legal.back_to_home')}
            </Link>
          </div>
        </div>
      </div>
    </Layout>
  );
};

export default LegalTerms;
