/**
 * Hero Image Component
 * 
 * Displays hero images with automatic light/dark mode detection.
 * Optimized with responsive images and lazy loading.
 */

import React from 'react';
import './HeroImage.css';

interface HeroImageProps {
  page?: 'home' | 'interviewer' | 'candidate';
  className?: string;
  priority?: boolean; // If true, eager load (for above-the-fold)
}

const HeroImage: React.FC<HeroImageProps> = ({ 
  className = '',
  priority = false
}) => {
  return (
    <picture className={`hero-image-container ${className}`}>
      {/* Dark mode - use PNG generated by AI */}
      <source 
        srcSet="/assets/heroes/hero-home-dark.png" 
        media="(prefers-color-scheme: dark)"
        type="image/png"
      />
      
      {/* Light mode - use PNG generated by AI */}
      <source 
        srcSet="/assets/heroes/hero-home-light.png" 
        media="(prefers-color-scheme: light)"
        type="image/png"
      />
      
      {/* Fallback - SVG placeholder */}
      <img 
        src="/assets/heroes/hero-home-light.svg"
        alt="ShortlistAI - AI-Powered CV Analysis"
        className="hero-image"
        loading={priority ? 'eager' : 'lazy'}
      />
    </picture>
  );
};

export default HeroImage;

