"""
PDF Branding Module for ShortlistAI.

Provides consistent branding elements (colors, logo, header, footer) for all PDF reports.
"""

from pathlib import Path
from typing import Optional, Tuple
from reportlab.lib import colors
from reportlab.lib.styles import ParagraphStyle
from reportlab.lib.enums import TA_LEFT, TA_CENTER, TA_RIGHT
from reportlab.lib.units import inch
from reportlab.platypus import Paragraph, Image, Table, TableStyle
from reportlab.pdfgen import canvas
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
from datetime import datetime
import logging

logger = logging.getLogger(__name__)


class ShortlistAIBranding:
    """
    ShortlistAI brand identity for PDF documents.
    
    Brand Colors:
    - AI Blue: #0066FF (primary)
    - Neural Purple: #7C3AED (secondary)
    - Success Green: #10B981
    - Warning Orange: #F59E0B
    - Error Red: #EF4444
    """
    
    # Brand Colors
    AI_BLUE = colors.HexColor('#0066FF')
    AI_BLUE_DARK = colors.HexColor('#3388FF')
    NEURAL_PURPLE = colors.HexColor('#7C3AED')
    NEURAL_PURPLE_LIGHT = colors.HexColor('#9F7AEA')
    
    # Semantic Colors
    SUCCESS_GREEN = colors.HexColor('#10B981')
    WARNING_ORANGE = colors.HexColor('#F59E0B')
    ERROR_RED = colors.HexColor('#EF4444')
    
    # Neutrals
    TEXT_PRIMARY_LIGHT = colors.HexColor('#111827')
    TEXT_SECONDARY_LIGHT = colors.HexColor('#6B7280')
    BG_LIGHT = colors.HexColor('#F8F9FA')
    BORDER_LIGHT = colors.HexColor('#E5E7EB')
    
    # Layout constants
    HEADER_HEIGHT = 1.9 * inch
    HEADER_CONTENT_PADDING = 0.25 * inch
    
    # Logo path
    _LOGO_PATH = None
    _FONTS_REGISTERED = False
    _FONT_FILES = {
        "Inter-Regular": "Inter-Regular.ttf",
        "Inter-Medium": "Inter-Medium.ttf",
        "Inter-SemiBold": "Inter-SemiBold.ttf",
        "Inter-Bold": "Inter-Bold.ttf",
    }
    _REGISTERED_FONTS: set[str] = set()
    _REQUIRED_FONTS = set(_FONT_FILES.keys())
    _FONT_DIRECTORIES = (
        ("src", "backend", "assets", "fonts"),
        ("backend", "assets", "fonts"),
        ("assets", "fonts"),
    )
    
    @classmethod
    def get_logo_path(cls) -> Optional[Path]:
        """Get path to ShortlistAI logo PNG."""
        if cls._LOGO_PATH is None:
            # Try multiple possible locations for the logo
            project_root = Path(__file__).resolve().parents[4]

            logo_paths = [
                # Preferred: branded app icon inside frontend public assets
                project_root / "src" / "frontend" / "public" / "assets" / "logos" / "app-icon-512.png",
                # Fallbacks: PWA icons generated by Vite
                project_root / "src" / "frontend" / "public" / "icons" / "icon-512x512.png",
                project_root / "src" / "frontend" / "public" / "icons" / "icon-384x384.png",
                # Root-level public folders (after build or alternative setups)
                project_root / "public" / "assets" / "logos" / "app-icon-512.png",
                project_root / "public" / "icons" / "icon-512x512.png",
                # Backend assets folder as last resort (allows custom deployments)
                project_root / "src" / "backend" / "assets" / "logo.png",
            ]

            for logo_path in logo_paths:
                if logo_path.exists():
                    cls._LOGO_PATH = logo_path
                    logger.info("ShortlistAI PDF logo resolved at %s", logo_path)
                    break
            else:
                logger.warning(
                    "ShortlistAI PDF logo not found. Searched paths: %s",
                    ", ".join(str(p) for p in logo_paths)
                )
        
        return cls._LOGO_PATH
    
    @classmethod
    def get_header_height(cls) -> float:
        """Return the reserved header height."""
        return cls.HEADER_HEIGHT
    
    @classmethod
    def get_content_top_padding(cls) -> float:
        """Vertical gap between header and body content."""
        return 0.35 * inch
    
    @classmethod
    def ensure_fonts_registered(cls) -> None:
        """Register Inter font family with ReportLab for consistent branding."""
        if cls._FONTS_REGISTERED:
            return

        project_root = Path(__file__).resolve().parents[4]
        font_dir: Optional[Path] = None

        for relative_parts in cls._FONT_DIRECTORIES:
            candidate = project_root.joinpath(*relative_parts)
            if candidate.exists():
                font_dir = candidate
                break

        if not font_dir:
            logger.warning("Inter font directory not found; falling back to default fonts.")
            cls._FONTS_REGISTERED = True  # Avoid repeating the search every call
            return

        missing_fonts = []
        for font_name, file_name in cls._FONT_FILES.items():
            font_path = font_dir / file_name
            if not font_path.exists():
                missing_fonts.append(str(font_path))
                continue

            try:
                pdfmetrics.registerFont(TTFont(font_name, str(font_path)))
            except Exception as exc:  # noqa: BLE001 - report unexpected registration issues
                logger.error("Failed to register font %s from %s: %s", font_name, font_path, exc)
            else:
                logger.info("Registered PDF font %s from %s", font_name, font_path)
                cls._REGISTERED_FONTS.add(font_name)

        if missing_fonts:
            logger.warning("Missing Inter font files for PDF generation: %s", ", ".join(missing_fonts))

        cls._FONTS_REGISTERED = True

    @classmethod
    def fonts_available(cls) -> bool:
        """Return True when Inter fonts have been registered."""
        return cls._REQUIRED_FONTS.issubset(cls._REGISTERED_FONTS)

    @classmethod
    def _font(cls, preferred: str, fallback: str) -> str:
        """Return the preferred Inter font when available, otherwise fallback."""
        return preferred if preferred in cls._REGISTERED_FONTS else fallback

    @classmethod
    def get_logo_image(cls, width: float = 0.7*inch, height: Optional[float] = None) -> Optional[Image]:
        """
        Get ShortlistAI logo as ReportLab Image.
        
        Args:
            width: Logo width in inches (default 0.7")
            height: Logo height (auto if None, maintains aspect ratio)
        
        Returns:
            Image object or None if logo not found
        """
        cls.ensure_fonts_registered()
        logo_path = cls.get_logo_path()
        
        if not logo_path:
            # Fallback to text logo
            from reportlab.platypus import Paragraph
            from reportlab.lib.styles import getSampleStyleSheet
            
            styles = getSampleStyleSheet()
            logo_style = ParagraphStyle(
                name='LogoStyle',
                parent=styles['Normal'],
                fontSize=20,
                fontName=cls._font('Inter-Bold', 'Helvetica-Bold'),
                textColor=cls.AI_BLUE,
                alignment=TA_CENTER
            )
            
            return Paragraph('<font color="#0066FF"><b>ShortlistAI</b></font>', logo_style)
        
        try:
            # Load PNG logo
            # If height not specified, maintain aspect ratio (logo is square)
            if height is None:
                height = width
            
            img = Image(str(logo_path), width=width, height=height)
            img.hAlign = 'CENTER'
            return img
            
        except Exception as e:
            logger.error(f"Error loading logo from {logo_path}: {e}")
            # Fallback to text
            from reportlab.platypus import Paragraph
            from reportlab.lib.styles import getSampleStyleSheet
            
            styles = getSampleStyleSheet()
            logo_style = ParagraphStyle(
                name='LogoStyle',
                parent=styles['Normal'],
                fontSize=20,
                fontName='Helvetica-Bold',
                textColor=cls.AI_BLUE,
                alignment=TA_CENTER
            )
            
            return Paragraph('<font color="#0066FF"><b>ShortlistAI</b></font>', logo_style)
    
    @classmethod
    def create_header(cls, canvas_obj, doc):
        """
        Create branded header for PDF pages.
        
        Args:
            canvas_obj: ReportLab canvas
            doc: Document object
        """
        cls.ensure_fonts_registered()
        # Save state
        canvas_obj.saveState()
        page_width, page_height = doc.pagesize
        header_height = cls.get_header_height()
        header_bottom = page_height - header_height

        # Clear background to avoid overlay artifacts
        canvas_obj.setFillColor(colors.white)
        canvas_obj.rect(0, header_bottom, page_width, header_height, stroke=0, fill=1)

        logo_size = 0.9 * inch
        logo_path = cls.get_logo_path()
        logo_x = doc.leftMargin
        logo_y = header_bottom + (header_height - logo_size) / 2

        if logo_path:
            canvas_obj.drawImage(
                str(logo_path),
                logo_x,
                logo_y,
                width=logo_size,
                height=logo_size,
                mask="auto"
            )
        else:
            # Draw a simple gradient placeholder if logo missing
            canvas_obj.setFillColor(cls.AI_BLUE)
            canvas_obj.circle(logo_x + logo_size / 2, logo_y + logo_size / 2, logo_size / 2, stroke=0, fill=1)

        wordmark_x = logo_x + logo_size + cls.HEADER_CONTENT_PADDING
        wordmark_baseline = logo_y + logo_size - 12
        primary_font = cls._font("Inter-Bold", "Helvetica-Bold")
        secondary_font = cls._font("Inter-Bold", "Helvetica-Bold")

        # Draw "Shortlist" in AI Blue
        canvas_obj.setFont(primary_font, 18)
        canvas_obj.setFillColor(cls.AI_BLUE)
        shortlist_text = "Shortlist"
        canvas_obj.drawString(wordmark_x, wordmark_baseline, shortlist_text)

        # Draw "AI" in Neural Purple just after "Shortlist"
        text_width = pdfmetrics.stringWidth(shortlist_text + " ", primary_font, 18)
        canvas_obj.setFont(secondary_font, 18)
        canvas_obj.setFillColor(cls.NEURAL_PURPLE)
        canvas_obj.drawString(wordmark_x + text_width, wordmark_baseline, "AI")

        # Tagline
        canvas_obj.setFont(cls._font("Inter-Medium", "Helvetica"), 9)
        canvas_obj.setFillColor(cls.TEXT_SECONDARY_LIGHT)
        canvas_obj.drawString(wordmark_x, logo_y + 10, "AI-Powered CV Analysis Platform")

        # Contact info aligned right
        contact_font = cls._font("Inter-Regular", "Helvetica")
        canvas_obj.setFont(contact_font, 8.5)
        canvas_obj.setFillColor(cls.TEXT_SECONDARY_LIGHT)
        contact_y = logo_y + logo_size - 8
        canvas_obj.drawRightString(
            page_width - doc.rightMargin,
            contact_y,
            "shortlistai.com"
        )
        canvas_obj.drawRightString(
            page_width - doc.rightMargin,
            contact_y - 11,
            "privacy@shortlistai.com"
        )

        # Accent line
        line_y = header_bottom + cls.HEADER_CONTENT_PADDING
        canvas_obj.setStrokeColor(cls.AI_BLUE)
        canvas_obj.setLineWidth(2)
        canvas_obj.line(doc.leftMargin, line_y, page_width - doc.rightMargin, line_y)
        
        # Restore state
        canvas_obj.restoreState()
    
    @classmethod
    def create_footer(cls, canvas_obj, doc):
        """
        Create branded footer for PDF pages.
        
        Args:
            canvas_obj: ReportLab canvas
            doc: Document object
        """
        cls.ensure_fonts_registered()
        # Save state
        canvas_obj.saveState()

        page_width, _ = doc.pagesize
        footer_height = 0.85 * inch
        footer_bottom = doc.bottomMargin - 0.35 * inch

        # Clean background
        canvas_obj.setFillColor(colors.white)
        canvas_obj.rect(0, footer_bottom, page_width, footer_height + 0.35 * inch, stroke=0, fill=1)

        # Divider line
        line_y = footer_bottom + footer_height
        canvas_obj.setStrokeColor(cls.BORDER_LIGHT)
        canvas_obj.setLineWidth(1)
        canvas_obj.line(
            doc.leftMargin,
            line_y,
            page_width - doc.rightMargin,
            line_y
        )

        # Shared baseline
        baseline_y = footer_bottom + (footer_height / 2)

        # Page number (center)
        page_num = canvas_obj.getPageNumber()
        canvas_obj.setFont(cls._font('Inter-Medium', 'Helvetica'), 9)
        canvas_obj.setFillColor(cls.TEXT_SECONDARY_LIGHT)
        canvas_obj.drawCentredString(
            doc.width / 2 + doc.leftMargin,
            baseline_y,
            f"Page {page_num}"
        )

        # Confidential notice (left)
        canvas_obj.setFont(cls._font('Inter-Medium', 'Helvetica-Oblique'), 8)
        canvas_obj.drawString(
            doc.leftMargin,
            baseline_y,
            "Confidential — For internal hiring use only"
        )

        # ShortlistAI branding (right)
        canvas_obj.setFont(cls._font('Inter-Regular', 'Helvetica'), 8)
        canvas_obj.drawRightString(
            page_width - doc.rightMargin,
            baseline_y,
            "shortlistai.com · privacy@shortlistai.com"
        )

        # Restore state
        canvas_obj.restoreState()
    
    @classmethod
    def get_custom_styles(cls, base_styles):
        """
        Get ShortlistAI branded paragraph styles.
        
        Args:
            base_styles: ReportLab StyleSheet
        
        Returns:
            Dict of custom styles
        """
        cls.ensure_fonts_registered()
        styles = {}
        
        # Branded Title
        styles['BrandedTitle'] = ParagraphStyle(
            name='BrandedTitle',
            parent=base_styles['Heading1'],
            fontSize=26,
            textColor=cls.AI_BLUE,
            spaceAfter=25,
            alignment=TA_CENTER,
            fontName=cls._font('Inter-Bold', 'Helvetica-Bold')
        )
        
        # Section Header with brand color
        styles['BrandedSectionHeader'] = ParagraphStyle(
            name='BrandedSectionHeader',
            parent=base_styles['Heading2'],
            fontSize=16,
            textColor=cls.AI_BLUE,
            spaceBefore=20,
            spaceAfter=12,
            fontName=cls._font('Inter-SemiBold', 'Helvetica-Bold'),
            borderWidth=0,
            borderColor=cls.AI_BLUE,
            borderPadding=0
        )
        
        # Subsection with purple accent
        styles['BrandedSubSection'] = ParagraphStyle(
            name='BrandedSubSection',
            parent=base_styles['Heading3'],
            fontSize=14,
            textColor=cls.NEURAL_PURPLE,
            spaceBefore=12,
            spaceAfter=8,
            fontName=cls._font('Inter-SemiBold', 'Helvetica-Bold')
        )
        
        # Highlight box (success)
        styles['SuccessBox'] = ParagraphStyle(
            name='SuccessBox',
            parent=base_styles['BodyText'],
            fontSize=11,
            fontName=cls._font('Inter-Medium', 'Helvetica'),
            textColor=colors.white,
            backColor=cls.SUCCESS_GREEN,
            borderPadding=10,
            spaceAfter=15,
            borderRadius=4
        )
        
        # Warning box
        styles['WarningBox'] = ParagraphStyle(
            name='WarningBox',
            parent=base_styles['BodyText'],
            fontSize=11,
            fontName=cls._font('Inter-Medium', 'Helvetica'),
            textColor=colors.white,
            backColor=cls.WARNING_ORANGE,
            borderPadding=10,
            spaceAfter=15,
            borderRadius=4
        )
        
        # Info box (AI Blue)
        styles['InfoBox'] = ParagraphStyle(
            name='InfoBox',
            parent=base_styles['BodyText'],
            fontSize=11,
            fontName=cls._font('Inter-Regular', 'Helvetica'),
            backColor=colors.HexColor('#E6F0FF'),  # Light blue
            borderColor=cls.AI_BLUE,
            borderWidth=1,
            borderPadding=10,
            spaceAfter=15,
            leftIndent=10,
            rightIndent=10
        )
        
        # Metadata style
        styles['Metadata'] = ParagraphStyle(
            name='Metadata',
            parent=base_styles['Normal'],
            fontSize=10,
            fontName=cls._font('Inter-Regular', 'Helvetica'),
            textColor=cls.TEXT_SECONDARY_LIGHT,
            alignment=TA_CENTER,
            spaceAfter=6
        )
        
        # Report code style
        styles['ReportCode'] = ParagraphStyle(
            name='ReportCode',
            parent=base_styles['Normal'],
            fontSize=14,
            fontName='Courier-Bold',
            textColor=cls.NEURAL_PURPLE,
            alignment=TA_CENTER,
            spaceAfter=20,
            backColor=colors.HexColor('#F3F4F6')
        )
        
        return styles
    
    @classmethod
    def create_branded_table_style(cls, has_header: bool = True) -> TableStyle:
        """
        Create branded table style.
        
        Args:
            has_header: Whether table has header row
        
        Returns:
            TableStyle with brand colors
        """
        cls.ensure_fonts_registered()
        header_font = cls._font('Inter-SemiBold', 'Helvetica-Bold')
        body_font = cls._font('Inter-Regular', 'Helvetica')
        style_commands = [
            # Grid
            ('GRID', (0, 0), (-1, -1), 0.5, cls.BORDER_LIGHT),
            ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
            ('LEFTPADDING', (0, 0), (-1, -1), 8),
            ('RIGHTPADDING', (0, 0), (-1, -1), 8),
            ('TOPPADDING', (0, 0), (-1, -1), 6),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
            ('FONTNAME', (0, 0), (-1, -1), body_font),
        ]
        
        if has_header:
            # Header row styling
            style_commands.extend([
                ('BACKGROUND', (0, 0), (-1, 0), cls.AI_BLUE),
                ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
                ('FONTNAME', (0, 0), (-1, 0), header_font),
                ('FONTSIZE', (0, 0), (-1, 0), 11),
                ('BOTTOMPADDING', (0, 0), (-1, 0), 10),
            ])
            
            # Alternating row colors
            style_commands.append(
                ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, cls.BG_LIGHT])
            )
        
        return TableStyle(style_commands)
    
    @classmethod
    def get_score_color(cls, score: float) -> colors.Color:
        """
        Get color for score based on value.
        
        Args:
            score: Score from 0-100
        
        Returns:
            Color object
        """
        if score >= 80:
            return cls.SUCCESS_GREEN
        elif score >= 60:
            return cls.WARNING_ORANGE
        else:
            return cls.ERROR_RED


# Singleton instance
_branding: Optional[ShortlistAIBranding] = None


def get_branding() -> ShortlistAIBranding:
    """Get global branding instance."""
    global _branding
    if _branding is None:
        _branding = ShortlistAIBranding()
        _branding.ensure_fonts_registered()
    return _branding

